#!/usr/bin/env bash
set -euo pipefail

expand_path() {
  case "$1" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s/%s\n' "$HOME" "${1#\~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

looks_like_git_url() {
  case "$1" in
    http://*|https://*|ssh://*|git@*:*|*.git) return 0 ;;
    *) return 1 ;;
  esac
}

private_overlay_source() {
  local overlay_ref="$1"
  local overlay_path
  overlay_path="$(expand_path "$overlay_ref")"

  if [ -d "$overlay_path" ]; then
    printf '%s\n' "$overlay_path"
    return 0
  fi

  if looks_like_git_url "$overlay_ref"; then
    local source_parent source_dir
    source_parent="${XDG_DATA_HOME:-$HOME/.local/share}"
    source_dir="$source_parent/chezmoi-private"

    if [ -d "$source_dir/.git" ]; then
      git -C "$source_dir" pull --ff-only
    else
      mkdir -p "$source_parent"
      git clone "$overlay_ref" "$source_dir"
    fi

    printf '%s\n' "$source_dir"
    return 0
  fi

  echo "Private overlay not found: $overlay_ref" >&2
  return 1
}

apply_private_overlay() {
  local answer overlay_ref overlay_source

  read -r -p "Apply a private dotfiles overlay too? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES) ;;
    *) return 0 ;;
  esac

  read -r -p "Private overlay path or Git URL [~/dotfiles-private]: " overlay_ref
  overlay_ref="${overlay_ref:-~/dotfiles-private}"
  overlay_source="$(private_overlay_source "$overlay_ref")"

  echo "--- Private overlay diff: $overlay_source ---"
  chezmoi --source "$overlay_source" diff || true

  read -r -p "Apply private overlay changes? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES) chezmoi --source "$overlay_source" apply ;;
    *) echo "Aborted private overlay before apply." ;;
  esac
}

sanitize_git_profile_name() {
  printf '%s\n' "$1" | tr -cs 'A-Za-z0-9._-' '-' | sed 's/^-*//; s/-*$//'
}

git_identity_file() {
  local file="$1"
  local name="$2"
  local email="$3"

  : > "$file"
  chmod 600 "$file"
  git config --file "$file" user.name "$name"
  git config --file "$file" user.email "$email"
}

configure_git_identities() {
  local answer git_config_dir identities_dir local_config tmp_config
  local has_global=false has_folder_identity=false

  read -r -p "Configure Git identity on this machine? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES) ;;
    *) return 0 ;;
  esac

  git_config_dir="$HOME/.config/git"
  identities_dir="$git_config_dir/identities"
  local_config="$git_config_dir/local.inc"
  mkdir -p "$identities_dir"

  if [ -e "$local_config" ]; then
    read -r -p "$local_config already exists. Replace it? [y/N] " answer
    case "$answer" in
      y|Y|yes|YES) ;;
      *) echo "Leaving existing Git identity config unchanged."; return 0 ;;
    esac
  fi

  tmp_config="$(mktemp)"
  {
    echo "# Local Git identity config. Generated by ~/dotfiles/install.sh."
    echo "# This file is intentionally not managed by chezmoi."
    echo
  } > "$tmp_config"

  read -r -p "Set a global/default Git identity? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES)
      local global_name global_email
      read -r -p "Global Git User (Display Name): " global_name
      read -r -p "Global Git Email: " global_email
      if [ -n "$global_name" ] && [ -n "$global_email" ]; then
        git config --file "$tmp_config" user.name "$global_name"
        git config --file "$tmp_config" user.email "$global_email"
        has_global=true
      else
        echo "Skipping global Git identity because name or email was blank."
      fi
      ;;
  esac

  read -r -p "Setup folder-specific Git identities? [y/N] " answer
  case "$answer" in
    y|Y|yes|YES)
      local index=1
      while true; do
        local profile_input profile_name profile_file profile_display_name profile_email repo_folder repo_folder_expanded repo_pattern

        read -r -p "[$index] Profile Name: " profile_input
        profile_name="$(sanitize_git_profile_name "$profile_input")"
        if [ -z "$profile_name" ]; then
          echo "Profile name must contain at least one letter or number."
          continue
        fi

        profile_file="$identities_dir/$profile_name.inc"
        read -r -p "[$index] Git User (Display Name): " profile_display_name
        read -r -p "[$index] Git Email: " profile_email
        read -r -p "[$index] Include repos under this folder: " repo_folder

        if [ -z "$profile_display_name" ] || [ -z "$profile_email" ] || [ -z "$repo_folder" ]; then
          echo "Skipping $profile_name because name, email, or folder was blank."
        else
          repo_folder_expanded="$(expand_path "$repo_folder")"
          case "$repo_folder_expanded" in
            /*) ;;
            *) repo_folder_expanded="$PWD/$repo_folder_expanded" ;;
          esac
          repo_folder_expanded="${repo_folder_expanded%/}"
          repo_pattern="$repo_folder_expanded/**"

          git_identity_file "$profile_file" "$profile_display_name" "$profile_email"
          {
            echo
            printf '[includeIf "gitdir:%s"]\n' "$repo_pattern"
            printf '\tpath = %s\n' "$profile_file"
          } >> "$tmp_config"

          has_folder_identity=true
          echo "$profile_name identity configured for repos under $repo_folder_expanded"
        fi

        read -r -p "Create another Git identity? [y/N] " answer
        case "$answer" in
          y|Y|yes|YES) index=$((index + 1)) ;;
          *) break ;;
        esac
      done
      ;;
  esac

  if [ "$has_global" != true ] && [ "$has_folder_identity" = true ]; then
    git config --file "$tmp_config" user.useConfigOnly true
  fi

  if [ "$has_global" = true ] || [ "$has_folder_identity" = true ]; then
    install -m 600 "$tmp_config" "$local_config"
    echo "Git identity config written to $local_config"
  else
    echo "No Git identity config written."
  fi

  rm -f "$tmp_config"
}

repo_url="${1:-}"
if ! command -v chezmoi >/dev/null 2>&1; then
  echo "Installing chezmoi..."
  if command -v pacman >/dev/null 2>&1; then
    sudo pacman -S --needed --noconfirm chezmoi
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install -y chezmoi
  else
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
    export PATH="$HOME/.local/bin:$PATH"
  fi
fi

if [ -n "$repo_url" ]; then
  chezmoi init "$repo_url"
else
  chezmoi init --source "$(cd "$(dirname "$0")" && pwd)"
fi

chezmoi diff || true
read -r -p "Apply these changes? [y/N] " answer
case "$answer" in
  y|Y|yes|YES)
    chezmoi apply
    configure_git_identities
    apply_private_overlay
    ;;
  *) echo "Aborted before apply." ;;
esac
