# --- Ghostty & Terminal Settings ---
set-option -g set-clipboard external
set-option -g allow-passthrough on
set-option -g mouse on
set-option -g extended-keys on
set-option -g extended-keys-format csi-u

set-option -g default-terminal "tmux-256color"
set-option -as terminal-features ",xterm-ghostty:RGB"
set-option -as terminal-features ",xterm-ghostty:usstyle"

# --- List of Plugins ---
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'

# Official Dracula Plugin (Replaces manual run-shell)
set-option -g @plugin 'dracula/tmux'

# Dracula Options (Customize what shows up on your status bar)
set-option -g @dracula-plugins "cpu-usage ram-usage time"
set-option -g @dracula-show-powerline true
set-option -g @dracula-show-flags true
set-option -g @dracula-show-left-icon session

# --- Initialize TMUX plugin manager (ALWAYS AT THE VERY BOTTOM) ---
run '~/.tmux/plugins/tpm/tpm'
